### ISSUE TITLE
Reproduction Instructions

### ISSUE THREAD

**Issue by yensunnn** [ChenDdon/AGBTcode#7]
Hello, after using "https://weilab.math.msu.edu/AGBT_Source/downstream_nn_models.tar.gz" from 'Reproduction Instructions', I was able to obtain 4 PT files. However when using torch.load for these PT files, I get an AttributeError for 'DeepNN'.

How/where do I import the 'DeepNN' class? I have tried searching this repo for it but to no avail.

Also, will the reproduction produce the similar results as mentioned in the paper? Or will there certain aspects of the code that is not included in the repo?

Thanks in advance

**Comment by ChenDdon** [comment]
Hi,

Thanks for reaching out. In order to reduce the usage of memory, we just uploaded one set of model weights. In order to load the weights, you need to construct the ANN model with the same model structure as listed in the paper's Supporting Information file. As described in 'Reproduction instructions', the best performance was the consensus of predicted values of **20** models (generated with different random seeds), so the single model may not achieve the best performance.
Fortunately, the AGBT features are robust enough, so you just need some simple machine-learning models, such as GBRT, RF, etc, and you can achieve similar results.
This work focuses on the AGBT features and its framework. For the downstream tasks, as described in the article, we did not over-adjust the hyperparameters, but just used some very general parameters to train these downstream tasks. You can build a neural network yourself as a downstream machine learning model by carefully tuning it, and the results will even be better than those in the paper.

I hope these address your concerns.

**Comment by yensunnn** [comment]
Thanks for the detailed explanation!
